source $HOME/.config/nvim/general.vim
source $HOME/.config/nvim/plugins.vim
"source $HOME/.config/nvim/coc-setup.vim
source $HOME/.config/nvim/keys.vim
source $HOME/.config/nvim/color.vim
source $HOME/.config/nvim/close-old-buffers.vim
source $HOME/.config/nvim/formatter-setup.lua
source $HOME/.config/nvim/lsp-setup.lua
source $HOME/.config/nvim/scripts.vim
"source $HOME/.config/nvim/async-make.lua
source $HOME/.config/nvim/make-tsc.lua
source $HOME/.config/nvim/commands.lua
